### PR TITLE
Update rest-client dependency

### PR DESCRIPTION
**Pull request by suzannehamilton**
- Add Jenkinsfile so that these changes can be tested on CI
- Upgrade the rest-client dependency to solve dependency resolution conflicts with gds-api-adapters, so that the latest version of gds-api-adapters can be used in info-frontend
- Release version 0.0.4

I've heard that we're deprecating this library, but removing it from info-frontend looked non-trivial (given that I haven't worked with either this library or info-frontend before), so I'm just updating it to be compatible with other libraries. It would still be good to revisit this and remove the project altogether, but I hope it's OK to leave that to people who know more about it.

https://trello.com/c/u1H1rgDA/525-some-finding-pages-are-still-being-tracked-as-thing

### CODE REVIEW

**Comment by alecgibson** [comment]
It might be nice to add a `CHANGELOG` file to this gem like the others? Also, I think we tend to bump versions in a separate commit. You may also need to use the [publishGem](https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk_jenkins/files/var/lib/jenkins/groovy_scripts/govuk_jenkinslib.groovy#L536-L586) function in your `Jenkinsfile` to publish it on Jenkins 2?

**Comment by suzannehamilton** [comment]
I've added a changelog. 👍 

The version bump is already in a separate commit - I just included it in the same PR because it didn't seem likely that anyone would open another PR on this project at the same time.

The `buildProject` function calls `publishGem` so it hopefully all just work when these changes are merged to master.

**Comment by alecgibson** [comment]
Great - in that case can you please remove the dependency on `gem_publisher` too?

**Comment by danielroseman** [comment]
I don't understand how this gem could be used anywhere, since the app it is a client for was retired a year ago.

**Comment by suzannehamilton** [comment]
@danielroseman It's a dependency of info-frontend, but it looks like info-frontend isn't actually using the url arbiter functionality. It's just using some of the HTTP [response](https://github.com/alphagov/govuk-client-url_arbiter/blob/master/lib/govuk/client/response.rb) and [error handling](https://github.com/alphagov/govuk-client-url_arbiter/blob/master/lib/govuk/client/errors.rb) helpers.

What do you think about just moving those helpers into info-frontend and getting rid of this gem?

**Comment by danielroseman** [comment]
Yes, potentially. Ideally it would be using the helpers from gds-api-adapters, but not sure how different those are or how much work it would take to convert.

**Comment by suzannehamilton** [comment]
@danielroseman I've tried replacing using gds-api-adapters instead: alphagov/info-frontend#65

**Comment by suzannehamilton** [comment]
The info-frontend change has been merged. @danielroseman: thanks for the suggestion to use gds-api-adapters instead. 👍 

I think this means that this repo can be retired altogether. I can't find any alphagov projects which still use it.

**Pull request closed without merging**
